# SPDX-License-Identifier: GPL-2.0-only
# VirtRTLab DKMS configuration
# Usage: sudo make dkms-add
#        sudo dkms build virtrtlab/0.1.0
#        sudo dkms install virtrtlab/0.1.0

PACKAGE_NAME="virtrtlab"
PACKAGE_VERSION="0.1.0"

BUILT_MODULE_NAME[0]="virtrtlab_core"
BUILT_MODULE_LOCATION[0]="kernel/"
DEST_MODULE_LOCATION[0]="/updates/virtrtlab"

BUILT_MODULE_NAME[1]="virtrtlab_uart"
BUILT_MODULE_LOCATION[1]="kernel/"
DEST_MODULE_LOCATION[1]="/updates/virtrtlab"

BUILT_MODULE_NAME[2]="virtrtlab_gpio"
BUILT_MODULE_LOCATION[2]="kernel/"
DEST_MODULE_LOCATION[2]="/updates/virtrtlab"

AUTOINSTALL="yes"
MAKE[0]="make -C kernel KDIR=${kernel_source_dir}"
CLEAN="make -C kernel KDIR=${kernel_source_dir} clean"
